// types/dashboard.ts
// Dashboard-specific types for the student learning experience

import { Video, Section, PersonalizedPath } from './course';

// ============================================
// USER & PROFILE
// ============================================

export interface DashboardUser {
  id: string;
  email: string;
  name: string | null;
  tier: 'basic' | 'personalized' | 'premium';
  createdAt: string;
  updatedAt: string;
}

// ============================================
// LEARNING PATH
// ============================================

export interface LearningPathModule {
  id: string;
  title: string;
  description: string;
  order: number;
  totalVideos: number;
  completedVideos: number;
  estimatedMinutes: number;
  isUnlocked: boolean;
  isCompleted: boolean;
  isCurrent: boolean;
  videos: LearningPathVideo[];
}

export interface LearningPathVideo {
  id: string;
  title: string;
  description?: string;
  duration: number; // seconds
  order: number;
  videoUrl?: string;
  thumbnailUrl?: string;
  isCompleted: boolean;
  isCurrent: boolean;
  lastPosition: number; // seconds - for resume
  completedAt?: string;
}

export interface LearningPath {
  id: string;
  userId: string;
  projectDescription: string;
  modules: LearningPathModule[];
  totalVideos: number;
  completedVideos: number;
  totalMinutes: number;
  completedMinutes: number;
  progressPercentage: number;
  createdAt: string;
  updatedAt: string;
}

// ============================================
// PROGRESS TRACKING
// ============================================

export interface VideoProgress {
  id: string;
  userId: string;
  videoId: string;
  moduleId: string;
  completed: boolean;
  lastPosition: number; // seconds
  completedAt?: string;
  createdAt: string;
  updatedAt: string;
}

export interface ModuleProgress {
  moduleId: string;
  totalVideos: number;
  completedVideos: number;
  progressPercentage: number;
  isCompleted: boolean;
}

// ============================================
// CONTINUE LEARNING (Hero Section)
// ============================================

export interface ContinueLearning {
  hasContent: boolean;
  currentVideo: LearningPathVideo | null;
  currentModule: LearningPathModule | null;
  nextVideo: LearningPathVideo | null;
  overallProgress: number;
  resumePosition: number; // seconds
}

// ============================================
// ACTIVITY & STATS
// ============================================

export interface ActivityEvent {
  id: string;
  type: 'video_started' | 'video_completed' | 'module_completed' | 'checkpoint_submitted' | 'streak_achieved';
  title: string;
  description?: string;
  metadata?: Record<string, any>;
  createdAt: string;
}

export interface StudentStats {
  totalProgress: number; // percentage
  videosCompleted: number;
  totalVideos: number;
  modulesCompleted: number;
  totalModules: number;
  minutesWatched: number;
  currentStreak: number; // days
  longestStreak: number;
  lastActiveAt?: string;
}

export interface DailyActivity {
  date: string; // ISO date string (YYYY-MM-DD)
  minutesWatched: number;
  videosCompleted: number;
}

// ============================================
// DASHBOARD STATE
// ============================================

export interface DashboardData {
  user: DashboardUser;
  learningPath: LearningPath | null;
  continueLearning: ContinueLearning;
  stats: StudentStats;
  recentActivity: ActivityEvent[];
  isLoading: boolean;
  error: string | null;
}

// ============================================
// API RESPONSES
// ============================================

export interface DashboardApiResponse {
  success: boolean;
  data?: DashboardData;
  error?: string;
}

export interface VideoProgressUpdateRequest {
  videoId: string;
  moduleId: string;
  position: number;
  completed?: boolean;
}

export interface VideoProgressUpdateResponse {
  success: boolean;
  progress?: VideoProgress;
  error?: string;
}

// ============================================
// EMPTY STATES
// ============================================

export type DashboardState = 
  | 'loading'
  | 'no_path' // User hasn't generated a learning path yet
  | 'path_generating' // Path is being generated by n8n
  | 'ready' // Has learning path, ready to learn
  | 'completed' // Completed all content
  | 'error';
