export type ExerciseBlockFamily = "ai_native" | "complementary" | "mode";

export type ExerciseBlockDemo = {
  id: string;
  name: string;
  family: ExerciseBlockFamily;
  levels: string[];
  profiles: string[];
  measures: string[];
  ratio: "ai-native" | "complementario" | "transversal";
  description: string;
  userAction: string;
  managerSignal: string;
  demo: {
    title: string;
    eyebrow: string;
    primary: string;
    items: string[];
    footer: string;
  };
};

export const exerciseBlockStats = {
  total: 24,
  aiNative: 15,
  complementary: 8,
  modes: 1,
  targetAiNativeRatio: "60-70%",
};

export const exerciseBlocks: ExerciseBlockDemo[] = [
  {
    id: "source_context_selection",
    name: "source / context selection",
    family: "ai_native",
    levels: ["N1", "N2", "N3"],
    profiles: ["marketing_growth", "sales_revops", "customer_success_support", "finance_fpa", "legal_compliance_privacy"],
    measures: ["datos", "juicio"],
    ratio: "ai-native",
    description: "El usuario decide que documentos, filas o fragmentos si entran al contexto de IA.",
    userAction: "seleccionar, excluir o transformar fuentes antes de usar IA",
    managerSignal: "sabe darle contexto suficiente a IA sin sobreexponer datos",
    demo: {
      title: "elige contexto para el modelo",
      eyebrow: "datos permitidos",
      primary: "Tu equipo quiere resumir 12 tickets enterprise. Selecciona que informacion entra al contexto.",
      items: ["ticket summary", "SLA contratado", "email personal del cliente", "nota interna del CSM"],
      footer: "emite: selected_sources, excluded_sensitive_fields, rationale",
    },
  },
  {
    id: "guided_prompt_builder",
    name: "guided prompt builder",
    family: "ai_native",
    levels: ["N1", "N2"],
    profiles: ["marketing_growth", "finance_fpa", "customer_success_support"],
    measures: ["contexto", "ejecucion_ia"],
    ratio: "ai-native",
    description: "Construye un prompt por piezas: objetivo, contexto, datos, restricciones y formato.",
    userAction: "armar instrucciones estructuradas sin depender de un textarea libre",
    managerSignal: "puede encuadrar una tarea individual con suficiente claridad",
    demo: {
      title: "arma el prompt por capas",
      eyebrow: "objetivo + limites",
      primary: "Genera un primer borrador de email para recuperar leads frios, sin prometer descuentos.",
      items: ["objetivo", "audiencia", "datos permitidos", "tono", "formato de salida"],
      footer: "emite: prompt_parts, missing_constraints, output_format",
    },
  },
  {
    id: "model_followup",
    name: "model follow-up",
    family: "ai_native",
    levels: ["N1", "N2", "N3"],
    profiles: ["marketing_growth", "sales_revops", "customer_success_support", "legal_compliance_privacy"],
    measures: ["validacion", "ejecucion_ia"],
    ratio: "ai-native",
    description: "Despues de una respuesta de IA, el usuario decide el siguiente pedido correcto.",
    userAction: "pedir aclaracion, evidencia, alternativas o correccion al modelo",
    managerSignal: "no acepta el primer output sin dirigir la iteracion",
    demo: {
      title: "elige el siguiente follow-up",
      eyebrow: "respuesta incompleta",
      primary: "El modelo propuso enviar outreach a todos los SQLs, pero no menciono aprobacion humana.",
      items: ["pide riesgos", "pide version mas corta", "pide approval gates", "acepta output"],
      footer: "emite: followup_intent, validation_depth, escalation_awareness",
    },
  },
  {
    id: "ai_output_annotation",
    name: "AI output annotation",
    family: "ai_native",
    levels: ["N1", "N2"],
    profiles: ["marketing_growth", "customer_success_support", "finance_fpa", "legal_compliance_privacy"],
    measures: ["validacion", "juicio"],
    ratio: "ai-native",
    description: "Marca errores, claims debiles, riesgos, sesgos o partes reutilizables de un output.",
    userAction: "anotar segmentos de una respuesta de IA",
    managerSignal: "detecta errores antes de publicar o actuar",
    demo: {
      title: "marca el output riesgoso",
      eyebrow: "revision de IA",
      primary: "La IA escribio: 'nuestro producto garantiza reducir churn 40% en 30 dias'.",
      items: ["claim no verificado", "tono agresivo", "dato sensible", "frase reutilizable"],
      footer: "emite: flagged_segments, claim_quality, correction_notes",
    },
  },
  {
    id: "ai_comparison",
    name: "AI comparison",
    family: "ai_native",
    levels: ["N1", "N2"],
    profiles: ["marketing_growth", "customer_success_support", "finance_fpa"],
    measures: ["validacion", "impacto"],
    ratio: "ai-native",
    description: "Compara dos outputs o modelos y decide cual usar, editar o rechazar.",
    userAction: "comparar A/B con criterios de calidad",
    managerSignal: "elige por utilidad y riesgo, no por gusto superficial",
    demo: {
      title: "compara dos versiones",
      eyebrow: "A/B output",
      primary: "Version A es persuasiva pero exagera beneficios. Version B es sobria pero poco accionable.",
      items: ["usar A", "usar B", "fusionar", "rechazar ambas"],
      footer: "emite: selected_output, tradeoff_reason, edit_plan",
    },
  },
  {
    id: "claim_source_check",
    name: "claim / source check",
    family: "ai_native",
    levels: ["N1", "N2"],
    profiles: ["marketing_growth", "finance_fpa", "legal_compliance_privacy"],
    measures: ["validacion"],
    ratio: "ai-native",
    description: "Verifica claims, metricas, citas, fuentes o supuestos antes de usar el output.",
    userAction: "clasificar cada claim como usable, requiere fuente o rechazar",
    managerSignal: "no deja que IA invente evidencia para cliente o board",
    demo: {
      title: "verifica claims",
      eyebrow: "fuentes y metricas",
      primary: "El memo dice que 'el CAC bajo 18%' pero el dashboard solo muestra spend y SQLs.",
      items: ["claim soportado", "requiere fuente", "calculo incompleto", "rechazar"],
      footer: "emite: claim_status, evidence_gap, source_needed",
    },
  },
  {
    id: "guardrail_builder",
    name: "guardrail builder",
    family: "ai_native",
    levels: ["N2", "N3"],
    profiles: ["sales_revops", "customer_success_support", "operations_automation", "legal_compliance_privacy"],
    measures: ["juicio", "datos"],
    ratio: "ai-native",
    description: "Define reglas que limitan acciones, datos, confidence, escalamiento y permisos.",
    userAction: "crear reglas de control para IA o agente",
    managerSignal: "sabe convertir riesgo en controles operables",
    demo: {
      title: "define guardrails",
      eyebrow: "control de agente",
      primary: "El agente puede redactar respuestas, pero no debe cerrar tickets ni enviar correos externos.",
      items: ["no enviar externo", "escalar si confidence < 0.75", "no usar PII", "log obligatorio"],
      footer: "emite: guardrails, thresholds, forbidden_actions",
    },
  },
  {
    id: "agent_brief_builder",
    name: "agent brief builder",
    family: "ai_native",
    levels: ["N3"],
    profiles: ["sales_revops", "customer_success_support", "operations_automation"],
    measures: ["contexto", "datos", "ejecucion_ia", "juicio"],
    ratio: "ai-native",
    description: "Define objetivo, inputs, outputs, limites, permisos y escalamiento de un agente.",
    userAction: "configurar un agente con autonomia limitada",
    managerSignal: "puede delegar sin perder control",
    demo: {
      title: "brief de agente",
      eyebrow: "N3 agentes",
      primary: "Configura un agente para priorizar follow-up comercial sin enviar nada al cliente.",
      items: ["objetivo", "inputs permitidos", "acciones prohibidas", "approval gates", "fallback"],
      footer: "emite: agent_objective, allowed_inputs, escalation_policy",
    },
  },
  {
    id: "permission_matrix",
    name: "permission matrix",
    family: "ai_native",
    levels: ["N2", "N3"],
    profiles: ["sales_revops", "operations_automation", "legal_compliance_privacy", "customer_success_support"],
    measures: ["datos", "juicio"],
    ratio: "ai-native",
    description: "Decide que puede leer, escribir, enviar, borrar, actualizar o escalar una IA.",
    userAction: "asignar permisos por accion y riesgo",
    managerSignal: "entiende limites de autonomia y permisos",
    demo: {
      title: "matriz de permisos",
      eyebrow: "leer / escribir / enviar",
      primary: "Selecciona que acciones puede ejecutar el agente sin aprobacion humana.",
      items: ["leer CRM", "leer notas internas", "crear borrador", "enviar email", "actualizar stage"],
      footer: "emite: permission_state, blocked_actions, approval_gates",
    },
  },
  {
    id: "workflow_builder",
    name: "workflow builder",
    family: "ai_native",
    levels: ["N2", "N3"],
    profiles: ["operations_automation", "sales_revops", "customer_success_support", "marketing_growth"],
    measures: ["ejecucion_ia", "impacto"],
    ratio: "ai-native",
    description: "Ordena trigger, condiciones, herramientas, aprobaciones, fallback y salida.",
    userAction: "construir una secuencia de automatizacion",
    managerSignal: "puede insertar IA en un proceso real sin romper handoffs",
    demo: {
      title: "construye el flujo",
      eyebrow: "trigger → gate → accion",
      primary: "Cuando entre un ticket enterprise, resumir contexto, sugerir respuesta y escalar si hay riesgo legal.",
      items: ["trigger", "AI summary", "approval gate", "send draft", "fallback humano"],
      footer: "emite: workflow_steps, gates, handoff_quality",
    },
  },
  {
    id: "automation_rule_builder",
    name: "automation rule builder",
    family: "ai_native",
    levels: ["N2"],
    profiles: ["operations_automation", "sales_revops", "marketing_growth"],
    measures: ["ejecucion_ia", "validacion"],
    ratio: "ai-native",
    description: "Define reglas tipo si pasa X, hacer Y, salvo Z.",
    userAction: "crear condiciones y excepciones de automatizacion",
    managerSignal: "no automatiza sin manejar excepciones",
    demo: {
      title: "regla de automatizacion",
      eyebrow: "if / then / unless",
      primary: "Si un lead abre 3 correos y visita pricing, crear tarea para AE salvo que pidio no contacto.",
      items: ["condicion", "accion", "excepcion", "owner", "log"],
      footer: "emite: rule_logic, exception_handling, owner_assignment",
    },
  },
  {
    id: "run_log_review",
    name: "run log review",
    family: "ai_native",
    levels: ["N3"],
    profiles: ["sales_revops", "customer_success_support", "operations_automation"],
    measures: ["validacion", "juicio"],
    ratio: "ai-native",
    description: "Revisa logs de agente o workflow y detecta loops, errores, costos o acciones peligrosas.",
    userAction: "marcar eventos que bloquean el piloto",
    managerSignal: "sabe supervisar sistemas, no solo lanzarlos",
    demo: {
      title: "revisa logs del dry-run",
      eyebrow: "supervision",
      primary: "El agente reintento 6 veces, incluyo notas internas y no registro metrica de exito.",
      items: ["retry loop", "datos sensibles", "sin metrica", "accion segura"],
      footer: "emite: flagged_logs, stop_conditions, monitoring_gap",
    },
  },
  {
    id: "escalation_triage",
    name: "escalation triage",
    family: "ai_native",
    levels: ["N2", "N3"],
    profiles: ["customer_success_support", "legal_compliance_privacy", "finance_fpa", "operations_automation"],
    measures: ["juicio"],
    ratio: "ai-native",
    description: "Decide cuando IA debe parar y pasar a humano, legal, manager o especialista.",
    userAction: "clasificar casos segun autoridad y riesgo",
    managerSignal: "no confunde ayuda de IA con autorizacion",
    demo: {
      title: "escala o continua",
      eyebrow: "decision de autoridad",
      primary: "Un cliente amenaza con demanda si se usa su informacion para entrenar modelos.",
      items: ["responder con IA", "escalar legal", "pedir mas datos", "cerrar ticket"],
      footer: "emite: escalation_route, authority_boundary, risk_reason",
    },
  },
  {
    id: "ai_assisted_memo",
    name: "AI-assisted memo",
    family: "ai_native",
    levels: ["N1", "N2", "N3"],
    profiles: ["marketing_growth", "sales_revops", "customer_success_support", "operations_automation", "finance_fpa", "legal_compliance_privacy"],
    measures: ["impacto", "contexto"],
    ratio: "ai-native",
    description: "Usa o corrige IA para convertir evidencia en una recomendacion ejecutiva.",
    userAction: "editar un memo para hacerlo claro, accionable y responsable",
    managerSignal: "traduce criterio tecnico en decision de negocio",
    demo: {
      title: "memo al manager",
      eyebrow: "decision ejecutiva",
      primary: "Recomienda si lanzar el piloto, con controles, metrica y siguiente paso.",
      items: ["decision", "controles", "metrica", "owner", "siguiente paso"],
      footer: "emite: recommendation, business_metric, owner_next_step",
    },
  },
  {
    id: "eval_test_case_builder",
    name: "eval / test case builder",
    family: "ai_native",
    levels: ["N2", "N3"],
    profiles: ["operations_automation", "sales_revops", "customer_success_support", "legal_compliance_privacy"],
    measures: ["validacion", "impacto"],
    ratio: "ai-native",
    description: "Define pruebas antes de activar un workflow o agente.",
    userAction: "crear casos de prueba, expected outputs y stop conditions",
    managerSignal: "prueba antes de poner IA en produccion",
    demo: {
      title: "disena la prueba",
      eyebrow: "eval antes de piloto",
      primary: "Antes de activar el agente, define 4 escenarios de prueba y que resultado esperas.",
      items: ["caso normal", "dato sensible", "baja confianza", "error de herramienta"],
      footer: "emite: test_cases, expected_outputs, pass_fail_rules",
    },
  },
  {
    id: "data_table_triage",
    name: "data table triage",
    family: "complementary",
    levels: ["N1", "N2", "N3"],
    profiles: ["sales_revops", "finance_fpa", "marketing_growth", "legal_compliance_privacy"],
    measures: ["datos"],
    ratio: "complementario",
    description: "Limpia, oculta, transforma o descarta datos antes de usarlos.",
    userAction: "decidir keep, drop, hash, bucketize o summarize por campo",
    managerSignal: "entiende calidad y minimizacion de datos",
    demo: {
      title: "triage de tabla",
      eyebrow: "CRM rows",
      primary: "Define que hacer con email, telefono, deal value, notas internas y stage.",
      items: ["keep", "drop", "hash", "bucketize", "summarize"],
      footer: "emite: field_transformations, pii_handling, data_quality_flags",
    },
  },
  {
    id: "dashboard_pivot_interpretation",
    name: "dashboard / pivot interpretation",
    family: "complementary",
    levels: ["N1", "N2"],
    profiles: ["finance_fpa", "marketing_growth", "sales_revops", "operations_automation"],
    measures: ["datos", "impacto"],
    ratio: "complementario",
    description: "Lee metricas, detecta anomalias y decide que dato importa.",
    userAction: "interpretar dashboard o tabla dinamica",
    managerSignal: "no confunde output de IA con evidencia numerica",
    demo: {
      title: "interpreta el dashboard",
      eyebrow: "metricas",
      primary: "MQL sube 22%, SQL baja 9%, CAC no esta calculado. Que conclusion puedes defender?",
      items: ["anomalia", "metrica faltante", "hipotesis", "decision"],
      footer: "emite: metric_interpretation, missing_data, business_implication",
    },
  },
  {
    id: "tradeoff_decision",
    name: "tradeoff decision",
    family: "complementary",
    levels: ["N1", "N2", "N3"],
    profiles: ["marketing_growth", "sales_revops", "customer_success_support", "operations_automation", "finance_fpa", "legal_compliance_privacy"],
    measures: ["juicio", "impacto"],
    ratio: "complementario",
    description: "Elige entre opciones reales donde todas tienen costo.",
    userAction: "seleccionar una accion defendible y explicar tradeoff",
    managerSignal: "decide bajo ambiguedad, no solo detecta errores",
    demo: {
      title: "elige configuracion",
      eyebrow: "tradeoff real",
      primary: "Velocidad maxima, piloto controlado, solo interno o pausar por compliance.",
      items: ["full auto", "draft + approval", "internal only", "pause"],
      footer: "emite: selected_option, tradeoff_reason, risk_acceptance",
    },
  },
  {
    id: "validation_checklist",
    name: "validation checklist",
    family: "complementary",
    levels: ["N1", "N2"],
    profiles: ["marketing_growth", "finance_fpa", "legal_compliance_privacy", "customer_success_support"],
    measures: ["validacion"],
    ratio: "complementario",
    description: "Construye o aplica checklist antes de publicar, enviar o automatizar.",
    userAction: "marcar checks obligatorios y faltantes",
    managerSignal: "sigue disciplina de calidad antes de actuar",
    demo: {
      title: "checklist antes de publicar",
      eyebrow: "control de calidad",
      primary: "Antes de mandar un reporte generado con IA al board, selecciona checks minimos.",
      items: ["fuente", "calculo", "fecha", "supuesto", "owner"],
      footer: "emite: checklist_selected, missing_checks, readiness_to_send",
    },
  },
  {
    id: "document_risk_annotation",
    name: "document / risk annotation",
    family: "complementary",
    levels: ["N1", "N2"],
    profiles: ["legal_compliance_privacy", "finance_fpa", "customer_success_support"],
    measures: ["validacion", "juicio"],
    ratio: "complementario",
    description: "Anota un contrato, policy, correo o respuesta para identificar riesgos y obligaciones.",
    userAction: "marcar clausulas, obligaciones, datos sensibles o puntos de escalamiento",
    managerSignal: "detecta riesgo documental antes de usar IA o responder con autoridad",
    demo: {
      title: "anota el documento",
      eyebrow: "riesgo legal",
      primary: "Un vendor pide usar datos de clientes para mejorar modelos. Marca riesgos, permisos y escalamiento.",
      items: ["dato sensible", "requiere DPA", "escalar privacy", "clausula aceptable"],
      footer: "emite: annotated_risks, escalation_points, obligation_flags",
    },
  },
  {
    id: "prioritization_ranking",
    name: "prioritization / ranking",
    family: "complementary",
    levels: ["N1", "N2"],
    profiles: ["sales_revops", "customer_success_support", "operations_automation", "marketing_growth"],
    measures: ["contexto", "impacto"],
    ratio: "complementario",
    description: "Ordena leads, tickets, riesgos o acciones con criterio de negocio.",
    userAction: "rankear elementos y justificar el criterio",
    managerSignal: "prioriza segun impacto y no segun lo mas facil",
    demo: {
      title: "prioriza acciones",
      eyebrow: "ranking",
      primary: "Ordena 5 cuentas para follow-up considerando deal size, urgencia y riesgo legal.",
      items: ["alto impacto", "alto riesgo", "bloqueado", "quick win"],
      footer: "emite: ranking_order, prioritization_reason, tradeoff_notes",
    },
  },
  {
    id: "stakeholder_response",
    name: "stakeholder response",
    family: "complementary",
    levels: ["N1", "N2", "N3"],
    profiles: ["marketing_growth", "sales_revops", "customer_success_support", "operations_automation", "finance_fpa", "legal_compliance_privacy"],
    measures: ["contexto", "impacto"],
    ratio: "complementario",
    description: "Responde a VP, cliente, legal, AE, soporte o manager con lenguaje claro.",
    userAction: "redactar respuesta corta para stakeholder especifico",
    managerSignal: "sabe adaptar criterio a audiencia y accion",
    demo: {
      title: "responde al stakeholder",
      eyebrow: "comunicacion",
      primary: "El VP pide activar el agente hoy. Contesta con decision, controles y riesgo residual.",
      items: ["decision", "razon", "control", "siguiente paso"],
      footer: "emite: stakeholder_fit, clarity, actionability",
    },
  },
  {
    id: "postmortem",
    name: "postmortem",
    family: "complementary",
    levels: ["N2", "N3"],
    profiles: ["operations_automation", "customer_success_support", "sales_revops", "legal_compliance_privacy"],
    measures: ["validacion", "juicio"],
    ratio: "complementario",
    description: "Explica que salio mal y como evitarlo despues de un fallo de IA o automatizacion.",
    userAction: "identificar causa raiz, control faltante y cambio operativo",
    managerSignal: "convierte error en aprendizaje operacional",
    demo: {
      title: "postmortem de fallo",
      eyebrow: "aprendizaje operacional",
      primary: "Un workflow envio 18 correos duplicados. Identifica causa, control faltante y prevencion.",
      items: ["causa raiz", "control faltante", "impacto", "prevencion"],
      footer: "emite: root_cause, corrective_action, prevention_plan",
    },
  },
  {
    id: "timer_deadline_mode",
    name: "timer / deadline mode",
    family: "mode",
    levels: ["N1", "N2", "N3"],
    profiles: ["marketing_growth", "sales_revops", "customer_success_support", "operations_automation", "finance_fpa", "legal_compliance_privacy"],
    measures: ["juicio", "impacto"],
    ratio: "transversal",
    description: "Modo opcional que agrega presion temporal a cualquier bloque o caso.",
    userAction: "resolver con deadline fijo, suave o por seccion",
    managerSignal: "mide velocidad con control, no rapidez vacia",
    demo: {
      title: "deadline del caso",
      eyebrow: "modo transversal",
      primary: "Quedan 12 minutos antes de la reunion con el VP. Decide que controles no puedes saltarte.",
      items: ["fixed timer", "soft deadline", "step timer", "overtime flag"],
      footer: "emite: elapsed_seconds, review_time_ratio, overtime_seconds",
    },
  },
];

export const exerciseBlockFamilies = [
  {
    id: "ai_native",
    name: "AI-native",
    description: "Usar, dirigir, revisar, configurar o supervisar IA como parte central del trabajo.",
  },
  {
    id: "complementary",
    name: "complementarios",
    description: "Aterrizan IA en datos, decisiones, comunicacion y procesos reales.",
  },
  {
    id: "mode",
    name: "modos transversales",
    description: "Capas opcionales como timer/deadline que modifican la presion del caso.",
  },
];
